name: Docker Build & Push

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # GitHub repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Required for identity challenge with sigstore/fulcio when running outside of PRs
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder for multi-platform images and cache support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log into the Docker registry (except on PRs)
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-dev') }}
          tags: |
            type=semver,pattern=v*.*,prefix=backend-

      # Build and push the backend Docker image
      - name: Build and push backend Docker image
        id: build-backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          dockerfile: ./backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Docker metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-dev') }}
          tags: |
            type=semver,pattern=v*.*,prefix=frontend-

      # Build and push the frontend Docker image
      - name: Build and push frontend Docker image
        id: build-frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          dockerfile: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
